### PR TITLE
Loop Music

### LINKED ISSUE #33: Loop song/Change song if music stopped (pygame module)
In the beginning of the program, it asks the user if they want to play music. If they say yes the music plays. There are 7 songs defined to play as of now (and any song can play at random) but some songs can range from 1 minute and some up to 3 minutes. The songs (especially the short ones), may get over while the user is still playing the game. So, we need to make it so that if in the beginning the user wants to play music and later while the program is running if the song stops. Automatically pick a new song or loop the song that was playing before.

Please check out music.py for more info.

### PR DESCRIPTION
**Pull request by Omppu42**
# Play different song after previous finishes

- Fixes #33 
- Plays different song when previous finishes
- Made some deaths to execute game_over function previously just printing
- Doesn't print Currently playing - *track name*. If I print it, the text goes into the answering space, which looks bad

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

<!---

## Checklist:

- [ ] My code follows the style guidelines of this project and have read CONTRIBUTING.md
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

# Screenshots

Original | Updated
:----------------------:|:-----------:
** original screenshot  | ** updated screenshot **

### CODE REVIEW

**Review by KendallDoesCoding — APPROVED** [review]
Perfect, but please resolve conflicts and if possible can you add the musicTimer.py file inside the /music directory?

**Comment by Omppu42** [comment]
Got you!

**Comment by KendallDoesCoding** [comment]
> Got you!

Thanks, will merge when done!

**Comment by KendallDoesCoding** [comment]
There are conflicts in "chapters.py" and "music.py" do you need any help resolving them?

**Comment by Omppu42** [comment]
It's telling me the conflicts are too complex to resolve in the web editor, how can I resolve them?

**Comment by KendallDoesCoding** [comment]
> It's telling me the conflicts are too complex to resolve in the web editor, how can I resolve them?

Run this in the command line, it should fix the issue:


```
git checkout -b Omppu42-main main
git pull https://github.com/Omppu42/Choose-Your-Own-Adventure-Game-issue33.git main
git checkout main
git merge --no-ff Omppu42-main
git push origin main
```

**Comment by Omppu42** [comment]
Hopefully that's it

**Comment by Omppu42** [comment]
Let me know if there are any problems.

**Comment by KendallDoesCoding** [comment]
Thanks for your contribution @Omppu42!!

**Comment by Omppu42** [comment]
Glad I was able to help! Thanks for your patience!

**Comment by KendallDoesCoding** [comment]
Just a question, is __init.py required or can I delete that file @Omppu42 ?

**Comment by Omppu42** [comment]
Looks like you can delete it. When i was testing it didn't work without it. Now I tried again deleting __init__.py, and it works perfectly fine.
So yes, you can delete it

**Comment by KendallDoesCoding** [comment]
Ok, I'll just do some testing to confirm that cause it should work for
everyone and even with a different OS. Will remove the file by tom if it's
not of any use.

**Pull request merged**
