### PR TITLE
Add GUI

### LINKED ISSUE #21: [FEATURE REQUEST] - Add a GUI
Add a GUI to this Python project to make it look amazing!!

### PR DESCRIPTION
**Pull request by Omppu42**
# New GUI

- Fixes #21 
- Added GUI
- New chapter system

# Additional Info
- Added credits to readme.md, check them. 'Other credits'. I'm not sure if they're nessesary.
- Test the code if it works on your machine too.
- Gitpod has no gui and no music. Couldn't get music to work with pygame. Needs some other library (Didn't do much testing though, maybe pygame will somehow work)

### CODE REVIEW

**Review by KendallDoesCoding — COMMENTED** [review]
I really love this, it's amazing! Just a few thoughts, let me know if you can do them, or will merge this:

- Little styling on the text, or at least some colours (instead of only Black)
- Maybe put the music icon on the right instead of left
- Make the music icon slightly smaller.
- Right now it prints the heading text in the terminal (game name/copyright), can we add a print statement/input that says "The game has launched" once Pygame has opened the game?, or if it doesn't open with 25-30 seconds due to a bug or something with pygame then just go to the terminal (old version of it) (if this is too much of a hassle, then no problem. We can just print the game has launched when the game opens)

I really appreciate the effort you took into this and so quickly!!.

Thanks,
KendallDoesCoding

**Comment by KendallDoesCoding** [comment]
After I put the review, it got these errors.

I played the game one time and when I quit and tried resetting I got this?

```
Traceback (most recent call last):
    from music_player import *
  File "c:\gitbash\Repos\Choose-Your-Own-Adventure-Game\music_player.py", line 9, in <module>
    from GUI.GUI import GUIInstance
  File "c:\gitbash\Repos\Choose-Your-Own-Adventure-Game\GUI\GUI.py", line 4, in <module>
    import chapters
  File "c:\gitbash\Repos\Choose-Your-Own-Adventure-Game\chapters.py", line 8, in <module>
    from GUI.GUI import GUIInstance
ImportError: cannot import name 'GUIInstance' from partially initialized module 'GUI.GUI' (most likely due to a circular import) (c:\gitbash\Repos\Choose-Your-Own-Adventure-Game\GUI\GUI.py)
PS C:\gitbash\Repos\Choose-Your-Own-Adventure-Game> & C:/Python310/python.exe c:/gitbash/Repos/Choose-Your-Own-Adventure-Game/chapters.py
pygame 2.2.0 (SDL 2.0.22, Python 3.10.6)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "c:\gitbash\Repos\Choose-Your-Own-Adventure-Game\chapters.py", line 7, in <module>
    from music_player import *
  File "c:\gitbash\Repos\Choose-Your-Own-Adventure-Game\music_player.py", line 9, in <module>
    from GUI.GUI import GUIInstance
  File "c:\gitbash\Repos\Choose-Your-Own-Adventure-Game\GUI\GUI.py", line 4, in <module>
    import chapters
  File "c:\gitbash\Repos\Choose-Your-Own-Adventure-Game\chapters.py", line 8, in <module>
    from GUI.GUI import GUIInstance
ImportError: cannot import name 'GUIInstance' from partially initialized module 'GUI.GUI' (most likely due to a circular import) (c:\gitbash\Repos\Choose-Your-Own-Adventure-Game\GUI\GUI.py)
```

**Comment by KendallDoesCoding** [comment]
> I really love this, it's amazing! Just a few thoughts, let me know if you can do them, or will merge this:
> 
> * Little styling on the text, or at least some colours (instead of only Black)
> * Maybe put the music icon on the right instead of left
> * Make the music icon slightly smaller.
> * Right now it prints the heading text in the terminal (game name/copyright), can we add a print statement/input that says "The game has launched" once Pygame has opened the game?, or if it doesn't open with 25-30 seconds due to a bug or something with pygame then just go to the terminal (old version of it) (if this is too much of a hassle, then no problem. We can just print the game has launched when the game opens).
> * Can you make it so that when users run files like chapters.py, music_player.py no errors show up and it just doesn't print or do anything? or at best it can print, "Please run main.py".
> * Is it possible to remove the "Hello from pygame community" message in terminal before program starts? I managed to remove it it before (if was part of music_player) by
> 
> ```
> import os
> os.environ["PYGAME_HIDE_SUPPORT_PROMPT"] = "hide"
> ```
> 
> But, for main.py it's still not going? Can we not remove it this time because the entire program is in pygame?
> 
> * Is it possible to put the logo as the icon for the app on running, because at the moment it is this:
>   image
> 
> I really appreciate the effort you took into this and so quickly!!.
> 
> Thanks, KendallDoesCoding

Please let me know @Omppu42

**Comment by Omppu42** [comment]
I wont add color suoport that's too much work I feel like. 
In readme.md it clearly says run main.py so I don't think it's nessesary to print anything if ran the wrong file. 
I changed the music icon location and size, will commit soon.
The program already runs the console version if it fails to create a window.
Everything else seems to be fine i can implement them.

**Comment by Omppu42** [comment]
For the errors you shouldn't be running chapters.py directly

**Comment by Omppu42** [comment]
Check these tell me if I missed something

**Comment by KendallDoesCoding** [comment]
> For the errors you shouldn't be running chapters.py directly

It's fixed. If you run chapters, it'll just run the main project.

**Comment by KendallDoesCoding** [comment]
> I wont add color suoport that's too much work I feel like.

I'll create another issue for that when this is merged.

**Review by KendallDoesCoding — APPROVED** [review]

**Comment by KendallDoesCoding** [comment]
Thanks for your contribution @Omppu42 . I really appreciate you!!

**Comment by Omppu42** [comment]
Just a quick note that the small icon for the pygame window and the taskbar icon look pretty pixely and aren't clear. Consider creating another picture that would look good when it's small. @KendallDoesCoding

**Comment by KendallDoesCoding** [comment]
> Just a quick note that the small icon for the pygame window and the taskbar icon look pretty pixely and aren't clear. Consider creating another picture that would look good when it's small. @KendallDoesCoding

even after #52?

**Comment by KendallDoesCoding** [comment]
well for taskbar it's bad but other then that, it's fine?

**Comment by Omppu42** [comment]
Maybe you should consider making like a icon where there is just the red man? Because in my opinion they both look terrible right now

**Comment by KendallDoesCoding** [comment]
> Maybe you should consider making like a icon where there is just the red man? Because in my opinion they both look terrible right now

for sure.

**Pull request merged**
