### PR TITLE
[Refactoring]: Seperation into chapters

### LINKED ISSUE #5: Improve/Simplify Code
I don't know Python too well (I would say i know around quarter of it) so I may've used a hard way of going around things instead of the easy way, so I require help to make the code more simple.

### PR DESCRIPTION
**Pull request by ChinoCodeDemon**
I seperated each segment into a function and also added a gameover function.
This will avoid too much repitition.
I won't take too much work away on this.
Have fun learning python.

This pull request is addressing #5

fixes #5

### CODE REVIEW

**Comment by ChinoCodeDemon** [comment]
restyled is pretty annoying

**Review by KendallDoesCoding — APPROVED** [review]
Thanks a lot! Code looks much better, I aren't that advanced with Python so didn't know how to do it so really appreciate your help.

**Comment by KendallDoesCoding** [comment]
> restyled is pretty annoying

I'll remove it, if you want. Was just trying to use stuff for free which I can get with the GitHub Student plan. What did it change exactly?

**Comment by KendallDoesCoding** [comment]
Thanks for your contribution!

**Comment by KendallDoesCoding** [comment]
> Have fun learning python.

thanks

**Comment by ChinoCodeDemon** [comment]
> I'll remove it, if you want. Was just trying to use stuff for free which I can get with the GitHub Student plan. What did it change exactly?

It enforces multiple formatters, which wouldn't compatible to each other.
A simple linter would be probably better, some commonly used ones are pylint and flake.
If you want i could setup a workflow file for that, just run it on your device and try out which fits your needs.

**Pull request merged**
