### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Raulj123**
in music_player.py all the dir to the music folder started with capital M? Is this a mistake since it starts w lower case?

### CODE REVIEW

**Review by KendallDoesCoding — CHANGES_REQUESTED** [review]
I only need it from when the game opens, make the game in full screen and play it till you win/lose the game. After that, stop the video.

**Comment by Raulj123** [comment]
How do you play the game? no matter what i entered it didnt do anyhting?

**Comment by KendallDoesCoding** [comment]
> How do you play the game? no matter what i entered it didnt do anyhting?

You must tap the white box, and enter your name.

**Comment by Raulj123** [comment]
Screen Shot 2023-05-03 at 11 42 05 PM
Is this running on your computer??

**Comment by KendallDoesCoding** [comment]
> Screen Shot 2023-05-03 at 11 42 05 PM
> 
> Is this running on your computer??

Yes, tap the white box, type your name and tap enter.

**Comment by KendallDoesCoding** [comment]
@Raulj123 any update?

**Pull request closed without merging**
