### PR TITLE
Added new choice function

### PR DESCRIPTION
**Pull request by SahilSinghTomar**
## New feature

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality.

# Proposed Changes
- Added a choice function for choosing between chapter river or bridge

## Checklist:

- [x] My code follows the style guidelines of this project and have read CONTRIBUTING.md
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by KendallDoesCoding — APPROVED** [review]
Wow, this made the entire project random. It selects any question (not specifically the first question!!)

**Review by KendallDoesCoding — CHANGES_REQUESTED** [review]
I found a issue with this, while it works, if random.random is set to (0, 1) it asks the first question of chapter_bridge() everytime, if it's (1,1) or (1,0) it asks the first question of chapter_river() everytime.

So, it's basically us picking the option in the code and it's not random.

**Comment by SahilSinghTomar** [comment]
How i don't get it
choices function randomly choosing between 0 and 1.
if choice is 0 its chapter_river
if choice is 1 its chapter_bridge

**Comment by SahilSinghTomar** [comment]
if this doesn't work we can randomly choose number between 1 to 100
it number is even run chapter_river
or else  chapter_bridge

**Comment by KendallDoesCoding** [comment]
I don't know how though, but everytime it is 0,1 it is chapter_bridge and
1,1 or 1,0 it is chapter_river.

*Thanks,*
*Kendall Does Coding*

*Portfolio <https://kendalldoescoding.gq>*
*Github <https://github.com/KendallDoesCoding>*
*Youtube* <https://kendalldoescoding.gq/codingYT>

**Comment by KendallDoesCoding** [comment]
try that?

*Thanks,*
*Kendall Does Coding*

*Portfolio <https://kendalldoescoding.gq>*
*Github <https://github.com/KendallDoesCoding>*
*Youtube* <https://kendalldoescoding.gq/codingYT>

**Comment by SahilSinghTomar** [comment]
random

if its completely random

**Comment by KendallDoesCoding** [comment]
> random
> 
> if its completely random

bro, what works for you doesn't work on my OS, very weird.

**Comment by KendallDoesCoding** [comment]
The changes I made just now works on my OS, does it work on yours?

I added a list of the definitions and then made it pick a random one.

**Comment by SahilSinghTomar** [comment]
dirt road is there to choose between left and right

choice is btw river and bridge

**Comment by SahilSinghTomar** [comment]
no, i only did changes for chapter river and bridge

**Comment by KendallDoesCoding** [comment]
> no, i only did changes for chapter river and bridge

Oh. In #19 we discussed that:

> in this feature we only need to randomize the left and right path. am i right

> like if user chooses left he can go both river or bridge chapter

I've implemented the changes in this PR where the chapters when game is started in randomize, can you implement the changes that it takes random questions from the chapter too?

Sorry for the inconvience.

**Comment by SahilSinghTomar** [comment]
can u explain with a example. i didn't get it

**Comment by KendallDoesCoding** [comment]
> can u explain with a example. i didn't get it

I wanted it so that when the user starts the game it chooses either chapter_River or chapter_bridge, random and asks questions from there. I have implemented those changes.

Can you implement the changes so that, in the chapters the questions asked are in different order, etc? (i think this is what you did earlier in this PR, but after my changes got implemented your changes don't work)

**Comment by KendallDoesCoding** [comment]
add changes in this branch with my changes implemented too: https://github.com/SahilSinghTomar/Choose-Your-Own-Adventure-Game/tree/new-feature

**Comment by KendallDoesCoding** [comment]
@SahilSinghTomar why? I had implemented changes in this PR.

**Comment by KendallDoesCoding** [comment]
oh, i gave you the wrong link. I meant to share other branch link, no worries. Make a PR of what you did earlier but also if you can make it choose random after the user starts game

**Comment by KendallDoesCoding** [comment]
made a new PR for this as you reverted ALL the changes (force-pushed) #29

**Comment by KendallDoesCoding** [comment]
@SahilSinghTomar okay, I have committed to "main" - Choose Random Chapter when game begins.

Now, can you make it so that in the specific chapters, it takes a random question, because after my changes were committed to "main" this PR doesn't work.

Sorry for the inconvenience and hassle, please take your time!

**Comment by SahilSinghTomar** [comment]
ok

**Comment by SahilSinghTomar** [comment]
i will do it sometime later
i have my sem exams so taking off from coding

**Comment by KendallDoesCoding** [comment]
No worries! All the best.

**Pull request closed without merging**
